zt:
  datasource:
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    entity-packages: com.zt.blog.model
    driver-class-name: com.mysql.cj.jdbc.Driver
swagger:
  enable: true
file:
  rootPath: D:\\upload
image:
  rootPath: D:\\upload\\images
spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  profiles:
    active: pro